version: '3.8'

services:
  dev-container:
    build:
      context: .
      args:
        SSH_USER: ${SSH_USER}
        SSH_PASSWORD: ${SSH_PASSWORD}
    image: dockerremotedeveloper:latest
    ports:
      - "${SSH_PORT}:22"
    env_file:
      - config.env
